email: email@example.com

services:
  - address: https://www.google.com
    status: all
    log: google.log
    notify: email
    interval: 120s
    timeout: 1s

  - address: https://httpstat.us/200
    status: [5*, 4*]
    log: mff.log
    notify: off
    interval: 3m30s
    timeout: 5s

  - address: https://httpstat.us/301
    log: _
    notify: false
    interval: 1m

  - address: https://httpstat.us/403
    log: _
    notify: false
    interval: 1m

  - address: https://httpstat.us/500
    log: _
    notify: false
    interval: 1m


