email: email@example.com
log: log.txt

services:
  - address: https://www.google.com
    status: any
    notify: email
    interval: 120s
    timeout: 3s

  - address: https://httpstat.us/200
    status: "[345].."
    notify: off
    interval: 10s
    timeout: 5s

  - address: https://httpstat.us/301
    status: 300
    notify: false
    interval: 1m

  - address: https://httpstat.us/403
    status: "[45].."
    notify: false
    interval: 15s

  - address: https://httpstat.us/500
    status: 500
    notify: email
    interval: 1m


