webhook: https://discord.com/api/webhooks/...
log: log.txt

services:
  - address: https://www.google.com
    status: any
    notify: discord
    interval: 120s
    timeout: 3s

  - address: https://httpstat.us/200
    status: "[345].."
    notify: discord
    interval: 60s

  - address: https://httpstat.us/301
    status: 300
    notify: false
    interval: 1m

  - address: https://httpstat.us/403
    status: "[45].."
    notify: discord
    interval: 5m

  - address: https://httpstat.us/500
    status: 500
    notify: discord
    interval: 1m


